### ISSUE TITLE
[BUG] Not able to scan the barcode of this image using this library, however able to scan it with the phone app

### ISSUE THREAD

**Issue by kotasudhakar** [undecaf/zbar-wasm#20] opened 2024-05-13 05:53 UTC
**Describe the bug**

Not able to detect barcodes in certain cases like in the image attached, while it is completely working barcode and tried to scan the same with some online barcode readers  and with my phone both worked fine.

**To Reproduce**
1. Open demo website -> https://undecaf.github.io/zbar-wasm/example/
2. and scan this below image with the barcode 
![2024-04-15_14-37](https://github.com/undecaf/zbar-wasm/assets/19781684/17dc98cd-68ee-4643-a0d9-f0c79a80e3a8)

A minimal working example that reproduces the behavior would be much appreciated.

Or else the environment in which the behavior occurs needs to be specified:
 - Which target environment (Node/browser/other)?
 - Browser
 - Which type of modules (ESM/CommonJS/other)?
 - Which framework(s)?
 - Which devtools, including their configuration files?
 - `package.json` content
 - Any other context about the problem

**Expected behavior**  

**Screenshots**

**Comment by undecaf** [comment] 2024-05-13 13:16
IMHO the quality of that image is just too low for being scanned by zbar.

Could you please tell me which online barcode readers you were using and which barcode type they reported? Thank you.

**Comment by kotasudhakar** [comment] 2024-05-15 10:57
This one was able to scan 

https://play.google.com/store/apps/details?id=com.gamma.scan&hl=en&gl=US

**Comment by undecaf** [comment] 2024-05-15 19:31
Thank you @kotasudhakar for the list.

https://online-barcode-reader.inliteresearch.com/ reports a module size of 1.8px which makes this quite an edge case.

https://nanonets.com/barcode-scanner did not scan the barcode at all, it just detected the characters above and below the barcode.

Since `zbar-wasm` uses the [Zbar barcode reader](https://github.com/mchehab/zbar) (compiled to WASM) in the background, there is nothing I can do in order to improve detection quality. I can only suggest that you open an issue at that project that suggests to improve detection for barcodes with very small module sizes.

**Comment by zcattacz** [comment] 2024-05-16 04:14
Hi @undecaf, maybe have a try on this one https://zxing-wasm-demo.deno.dev/, when you switch the binarizer to `FixedThrethold` mode, it works. Clicking on the green circle on the upper right corner displays the decoded detail. 

I found binarizer pre-processing extremely helpful. Some of the QR code with parts scratched off, can still be read by pyZBar after the proper blur and binarization. But the settings varies for each different case and searching for the correct parameter takes many tries. cv2.adaptiveThreshold seems to work better but it's more time consuming depending on the parameter, which could take 150ms+ on an i5 PC.

I think for live scanners to work reasonably well, blur and binarization pre-processing are necessary. But due to the real time processing and live sampling, there is a line to draw for  responsiveness and super-detection on poor samples.

I showed your demo site to my peers and asked them to try, the general response is 1D 128 code works surprisingly well to at least usable, QRCODE code is generally barely usable, but some phone app works pretty well on them. (my conclusion from initial investigation, most tested poor performance QR codes are printed on water proof PET labels, such QR codes are prone to have uneven blackness due to the ink and surface property, which makes pre-processing necessary.).

So I really hope this project can add some smaller implementation for blur and adaptiveThreshold to enhance QRCODE detection. OpenCV is so big, but I don't know what other alternative is available as readily available wasm lib. The compiling environment seems to take several GB, which is not available on my current machine. :(

**Comment by undecaf** [comment] 2024-05-23 19:17
Thank you @kotasudhakar, @zcattacz for your contributions to this issue.

IMHO, it is not a bug if a scanner is not able to recognize a barcode because of low image quality -- it is just a consequence of the amount of detection effort in the scanning algorithm.

`zbar-wasm` is intended to be fast enough to scan barcodes in mobile browsers from the video stream of the camera. If real-time scanning is not required, detection quality could be improved by [preprocessing images in JS](https://github.com/search?q=image+processing+language%3AJavaScript&type=repositories&l=JavaScript&s=stars&o=desc) before passing them to the scanner, but this is outside the scope of `zbar-wasm`.

Therefore I hope you understand that I am closing this issue.

**Closed by undecaf** 2024-05-23 19:17 UTC
Labels: bug
